version: '3.4'

networks:
  dev:
    driver: bridge

services:
  sapiconfigapi:
    image: docker.io/library/sapiconfigapi 
    depends_on:
      - "sapiconfig_db"
    container_name: sapiconfigapi-services
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__MyConnectionString=User ID=postgres;Password=postgres;Server=sapiconfig_db;Port=5432;Database=<NAME-DB>; IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  sapiconfig_db:
    image: postgres:14.9
    container_name: sapiconfig_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sapiconfig
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
volumes:
  app_data: